#!/bin/bash
# Remotion Superpowers — Linux Studio Launcher
# Installs a desktop entry so Remotion Studio can be started from the
# application grid (GNOME/KDE/XFCE...) instead of a terminal command.
#
# Usage:
#   ./install-studio-launcher.sh [--project DIR] [--port N] [--name NAME]
#   ./install-studio-launcher.sh --uninstall [--project DIR]

set -o pipefail

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

PROJECT="$PWD"
PORT=3000
NAME=""
UNINSTALL=0

while [ $# -gt 0 ]; do
    case "$1" in
        --project) PROJECT="$2"; shift 2 ;;
        --port)    PORT="$2"; shift 2 ;;
        --name)    NAME="$2"; shift 2 ;;
        --uninstall) UNINSTALL=1; shift ;;
        -h|--help) sed -n '2,10p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

echo ""
echo "🎬 Remotion Superpowers — Studio Launcher"
echo "=========================================="
echo ""

# --- Platform guard ---
if [ "$(uname -s)" != "Linux" ]; then
    echo -e "  ${RED}✗${NC} This installer targets Linux desktops (XDG .desktop entries)."
    echo "    On macOS, use Automator or a .app wrapper instead."
    exit 1
fi

# --- Resolve project ---
PROJECT="$(cd "$PROJECT" 2>/dev/null && pwd)" || {
    echo -e "  ${RED}✗${NC} Project directory not found."
    exit 1
}

BIN_DIR="${XDG_BIN_HOME:-$HOME/.local/bin}"
APP_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
ICON_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor/scalable/apps"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}"

SLUG="$(basename "$PROJECT" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '-' | sed 's/-\{1,\}/-/g;s/^-//;s/-$//')"
[ -z "$SLUG" ] && SLUG="project"
ID="remotion-studio-$SLUG"
LAUNCHER="$BIN_DIR/$ID"
DESKTOP="$APP_DIR/$ID.desktop"
[ -z "$NAME" ] && NAME="Remotion Studio ($(basename "$PROJECT"))"

# --- Uninstall ---
if [ $UNINSTALL -eq 1 ]; then
    "$LAUNCHER" stop 2>/dev/null
    rm -f "$LAUNCHER" "$DESKTOP"
    command -v update-desktop-database >/dev/null && update-desktop-database "$APP_DIR" 2>/dev/null
    echo -e "  ${GREEN}✓${NC} Removed $NAME"
    echo ""
    exit 0
fi

# --- Validate it is a Remotion project ---
if ! ls "$PROJECT"/remotion.config.* >/dev/null 2>&1; then
    echo -e "  ${RED}✗${NC} No remotion.config.* in $PROJECT"
    echo "    Run this from a Remotion project, or pass --project DIR."
    echo "    Create one first with: npx create-video@latest"
    exit 1
fi
echo -e "  ${GREEN}✓${NC} Remotion project: $PROJECT"

# --- Detect package manager from the lockfile ---
if   [ -f "$PROJECT/pnpm-lock.yaml" ];    then PM="pnpm"
elif [ -f "$PROJECT/yarn.lock" ];         then PM="yarn"
elif [ -f "$PROJECT/bun.lockb" ];         then PM="bun"
elif [ -f "$PROJECT/package-lock.json" ]; then PM="npm"
else PM="npx"
fi
case "$PM" in
    npx)  DEV_CMD="npx remotion studio --port $PORT" ;;
    yarn) DEV_CMD="yarn remotion studio --port $PORT" ;;
    bun)  DEV_CMD="bun x remotion studio --port $PORT" ;;
    *)    DEV_CMD="$PM exec remotion studio --port $PORT" ;;
esac
echo -e "  ${GREEN}✓${NC} Package manager: $PM"

if ! command -v "$PM" >/dev/null 2>&1 && [ "$PM" != "npx" ]; then
    echo -e "  ${YELLOW}!${NC} $PM is not on PATH — the launcher will fail until it is."
fi

# --- Detect a terminal emulator for the "View Log" action ---
TERM_CMD=""
for t in x-terminal-emulator gnome-terminal ptyxis konsole xfce4-terminal alacritty kitty foot xterm; do
    if command -v "$t" >/dev/null 2>&1; then
        case "$t" in
            konsole|xterm|alacritty|kitty|foot) TERM_CMD="$t -e" ;;
            *) TERM_CMD="$t --" ;;
        esac
        break
    fi
done

mkdir -p "$BIN_DIR" "$APP_DIR" "$ICON_DIR" "$STATE_DIR"

# --- Icon (shared by every project's launcher) ---
cat > "$ICON_DIR/remotion-studio.svg" <<'SVG'
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128">
  <rect width="128" height="128" rx="28" fill="#0B84F3"/>
  <circle cx="64" cy="64" r="34" fill="none" stroke="#fff" stroke-width="7"/>
  <path d="M55 47 L86 64 L55 81 Z" fill="#fff"/>
</svg>
SVG

# --- Launcher script ---
cat > "$LAUNCHER" <<LAUNCHER_EOF
#!/usr/bin/env bash
# Generated by remotion-superpowers install-studio-launcher.sh — do not edit by hand.
# The studio server runs fully detached, so closing a window never kills it.
set -u

PROJECT="\${REMOTION_PROJECT:-$PROJECT}"
PORT="\${REMOTION_PORT:-$PORT}"
URL="http://localhost:\$PORT"
LOG="$STATE_DIR/$ID.log"
PIDFILE="$STATE_DIR/$ID.pid"

up()  { curl -fsS -o /dev/null --max-time 2 "\$URL"; }
say() { notify-send -a "Remotion Studio" -i remotion-studio "$NAME" "\$1" 2>/dev/null; }

case "\${1:-start}" in
    stop)
        [ -f "\$PIDFILE" ] && kill -- "-\$(cat "\$PIDFILE")" 2>/dev/null
        rm -f "\$PIDFILE"
        say "Server stopped."
        exit 0 ;;
    log)
        exec ${TERM_CMD:-x-terminal-emulator --} bash -c "tail -n 200 -f '\$LOG'" ;;
esac

# Already serving? Just reopen the tab.
if up; then xdg-open "\$URL" >/dev/null 2>&1 & exit 0; fi

cd "\$PROJECT" || { say "Project not found: \$PROJECT"; exit 1; }

# Detached session so no terminal owns the server.
: > "\$LOG"
setsid bash -c '[ -f ~/.remotion-env ] && . ~/.remotion-env; exec $DEV_CMD --no-open' \\
    >>"\$LOG" 2>&1 < /dev/null &
echo \$! > "\$PIDFILE"

for _ in \$(seq 1 90); do
    up && { xdg-open "\$URL" >/dev/null 2>&1 & exit 0; }
    kill -0 "\$(cat "\$PIDFILE")" 2>/dev/null || break
    sleep 1
done

say "Failed to start. Last log lines:
\$(tail -n 5 "\$LOG")"
exit 1
LAUNCHER_EOF
chmod +x "$LAUNCHER"

# --- Desktop entry ---
cat > "$DESKTOP" <<DESKTOP_EOF
[Desktop Entry]
Type=Application
Name=$NAME
GenericName=Video Editor
Comment=Preview and render Remotion compositions in the browser
Exec=$LAUNCHER
Icon=remotion-studio
Terminal=false
Categories=AudioVideo;Video;
Keywords=remotion;video;render;studio;composition;
StartupNotify=true
Actions=Stop;Log;

[Desktop Action Stop]
Name=Stop Server
Exec=$LAUNCHER stop

[Desktop Action Log]
Name=View Log
Exec=$LAUNCHER log
DESKTOP_EOF

command -v update-desktop-database >/dev/null && update-desktop-database "$APP_DIR" 2>/dev/null
command -v gtk-update-icon-cache  >/dev/null && gtk-update-icon-cache -f -t "${XDG_DATA_HOME:-$HOME/.local/share}/icons/hicolor" 2>/dev/null

if command -v desktop-file-validate >/dev/null 2>&1; then
    if desktop-file-validate "$DESKTOP" 2>/dev/null; then
        echo -e "  ${GREEN}✓${NC} Desktop entry valid"
    else
        echo -e "  ${YELLOW}!${NC} Desktop entry has warnings (it will still work)"
    fi
fi

echo -e "  ${GREEN}✓${NC} Installed: $DESKTOP"
echo ""
echo "  Press Super and type \"remotion\" to launch."
echo "  Right-click the icon for Stop Server / View Log."
echo ""

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo -e "  ${YELLOW}!${NC} $BIN_DIR is not on your PATH."
       echo "    The desktop entry works regardless (it uses the full path),"
       echo "    but add it to run '$ID' from a shell."
       echo "" ;;
esac
